// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pzjmikqadtrapidwzvkx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB6am1pa3FhZHRyYXBpZHd6dmt4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5OTUxNDUsImV4cCI6MjA2OTU3MTE0NX0.tye56-IeqyzrQ47jDetHKorvII3JqnqrIROO7WeirF0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});